version: '3.3'

services:
  db:
    image: mysql
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "notes_bt"
    ports:
      - '3306:3306'
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - my-db
      - ./mysql-init.sql:/tmp/mysql-init.sql
    networks:
      - bridgeNet

  web:
    build: .
    ports: 
      - '8080:8080'
    networks:
      - bridgeNet
    depends_on:
      db:
        condition: service_healthy

networks:
  bridgeNet:
    driver: bridge